{% set name = "kfp" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a330a65c2b57611e812614dce4e7dd81c9d77102afb3e4ab1305ba79bcf8f719

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dsl-compile = kfp.compiler.main:main
    - kfp=kfp.__main__:main


requirements:
  host:
    - python >=3.6.1
    - pip
  run:
    - python >=3.6.1
    - absl-py >=0.9,<=0.11
    - PyYAML >=5.3,<6
    - google-cloud-storage >=1.20.0,<2
    - python-kubernetes >=8.0.0,<13
    - google-api-python-client >=1.7.8,<2
    - google-auth >=1.6.1,<2
    - requests-toolbelt >=0.8.0,<1
    - cloudpickle >=1.3.0,<2
    - kfp-server-api >=1.1.2,<2.0.0
    - jsonschema >=3.0.1,<4
    - tabulate >=0.8.6,<1
    - click >=7.1.1,<8
    - Deprecated >=1.2.7,<2
    - strip-hints >=0.1.8,<1
    - docstring_parser >=0.7.3,<1
    - kfp-pipeline-spec >=0.1.9,<0.2.0
    - fire >=0.3.1,<1
    - protobuf >=3.13.0,<4

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - kfp

about:
  home: https://github.com/kubeflow/pipelines
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    Reusable end-to-end ML workflows built using the Kubeflow Pipelines SDK.
  description: |
    Kubeflow is a machine learning (ML) toolkit that is dedicated to making
    deployments of ML workflows on Kubernetes simple, portable, and scalable.
    Kubeflow pipelines are reusable end-to-end ML workflows built using the
    Kubeflow Pipelines SDK.

  doc_url: https://www.kubeflow.org/docs/pipelines/
  dev_url: https://github.com/kubeflow/pipelines/tree/master/sdk/python

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - tanguycdls
    - radcheb
    - ckadner
    - manuelwalserqc
