{% set name = "kfp" %}
{% set version = "2.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kfp-{{ version }}.tar.gz
  sha256: 7195019246f800fb842bb071c8d3a106ca3d2e812540f90a6b23c3ed19207ae5

build:
  noarch: python
  entry_points:
    - dsl-compile = kfp.cli.compile_:main
    - kfp=kfp.cli.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - click >=8.0.0,<9
    - docstring_parser >=0.7.3,<1
    - google-api-core >=1.31.5,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-auth >=1.6.1,<3
    - google-cloud-storage >=2.2.1,<3
    - kfp-pipeline-spec ==0.5.0
    - kfp-server-api >=2.1.0,<2.4.0
    - python-kubernetes >=8.0.0,<31
    - protobuf >=4.21.1,<5
    - pyyaml >=5.3,<7
    - requests-toolbelt >=0.8.0,<1
    - tabulate >=0.8.6,<1
    - urllib3 <2.0.0
    - typing-extensions >=3.7.4,<5

test:
  imports:
    - kfp
  commands:
    - pip check
    - kfp dsl compile --help
    - kfp --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kubeflow/pipelines
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    Reusable end-to-end ML workflows built using the Kubeflow Pipelines SDK.
  description: |
    Kubeflow is a machine learning (ML) toolkit that is dedicated to making
    deployments of ML workflows on Kubernetes simple, portable, and scalable.
    Kubeflow pipelines are reusable end-to-end ML workflows built using the
    Kubeflow Pipelines SDK.

  doc_url: https://www.kubeflow.org/docs/pipelines/
  dev_url: https://github.com/kubeflow/pipelines/tree/master/sdk/python

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - tanguycdls
    - radcheb
    - ckadner
    - manuelwalserqc
    - tarrade
    - alanhdu
