{% set name = "kfp" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05f2b2fe3dc058d1fe7aab52adc48fc5c0f030bb6e8ce36b0ce995ddc41dd20f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dsl-compile = kfp.compiler.main:main
    - kfp=kfp.__main__:main


requirements:
  host:
    - python >=3.5.3
    - pip
  run:
    - python >=3.5.3
    - PyYAML
    - google-cloud-storage >=1.13.0
    - python-kubernetes >=8.0.0,<12.0.0
    - google-auth >=1.6.1
    - requests-toolbelt >=0.8.0
    - cloudpickle
    - kfp-server-api >=0.2.5,<2.0.0
    - jsonschema >=3.0.1
    - tabulate
    - click
    - Deprecated
    - strip-hints

test:
  imports:
    - kfp

about:
  home: https://github.com/kubeflow/pipelines
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    Reusable end-to-end ML workflows built using the Kubeflow Pipelines SDK.
  description: |
    Kubeflow is a machine learning (ML) toolkit that is dedicated to making
    deployments of ML workflows on Kubernetes simple, portable, and scalable.
    Kubeflow pipelines are reusable end-to-end ML workflows built using the
    Kubeflow Pipelines SDK.

  doc_url: https://www.kubeflow.org/docs/pipelines/
  dev_url: https://github.com/kubeflow/pipelines/tree/master/sdk/python

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - tanguycdls
    - radcheb
