{% set name = "kfp" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63f853c6696ca9e10bf2857b806cd8e435bae0ac19ba89a633e2038638137a73

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dsl-compile = kfp.compiler.main:main
    - kfp=kfp.__main__:main


requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - absl-py >=0.9,<2
    - PyYAML >=5.3,<7
    # Pin google-api-core version for the bug fixing in 1.31.5
    # https://github.com/googleapis/python-api-core/releases/tag/v1.31.5
    - google-api-core >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    # `Blob.from_string` was introduced in google-cloud-storage 1.20.0
    # https://github.com/googleapis/python-storage/blob/master/CHANGELOG.md#1200
    - google-cloud-storage >=1.20.0,<3
    - python-kubernetes >=8.0.0,<26
    # google-api-python-client v2 doesnt work for private dicovery by default:
    # https://github.com/googleapis/google-api-python-client/issues/1225#issuecomment-791058235
    - google-api-python-client >=1.7.8,<2
    - google-auth >=1.6.1,<3
    - requests-toolbelt >=0.8.0,<1
    - cloudpickle >=2.0.0,<3
    # Update the upper version whenever a new major version of the
    # kfp-server-api package is released.
    # Update the lower version when kfp sdk depends on new apis/fields in
    # kfp-server-api.
    # Note, please also update ./requirements.in
    - kfp-server-api >=1.1.2,<2.0.0
    - jsonschema >=3.0.1,<5
    - tabulate >=0.8.6,<1
    - click >=7.1.2,<9
    - deprecated >=1.2.7,<2
    - strip-hints >=0.1.8,<1
    - docstring_parser >=0.7.3,<1
    - kfp-pipeline-spec >=0.1.16,<0.2.0
    - fire >=0.3.1,<1
    - protobuf >=3.13.0,<4
    - uritemplate >=3.0.1,<4
    # pin to avoid break in requests-toolbelt due to https://github.com/psf/requests/commit/2ad18e0e10e7d7ecd5384c378f25ec8821a10a29
    - urllib3 <2
    - pydantic >=1.8.2,<2
    - typer >=0.3.2,<1.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - kfp

about:
  home: https://github.com/kubeflow/pipelines
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    Reusable end-to-end ML workflows built using the Kubeflow Pipelines SDK.
  description: |
    Kubeflow is a machine learning (ML) toolkit that is dedicated to making
    deployments of ML workflows on Kubernetes simple, portable, and scalable.
    Kubeflow pipelines are reusable end-to-end ML workflows built using the
    Kubeflow Pipelines SDK.

  doc_url: https://www.kubeflow.org/docs/pipelines/
  dev_url: https://github.com/kubeflow/pipelines/tree/master/sdk/python

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - tanguycdls
    - radcheb
    - ckadner
    - manuelwalserqc
    - tarrade
    - alanhdu
