{% set name = "kfp" %}
{% set version = "1.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12b8e98e9e6ad4a56e20afaa4993ec4c3e80e86f84d2f5e32b92f7419869c45c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dsl-compile = kfp.compiler.main:main
    - kfp=kfp.__main__:main


requirements:
  host:
    - python >=3.5.3
    - pip
  run:
    - python >=3.5.3
    - PyYAML >=5.3
    - google-cloud-storage >=1.13
    - python-kubernetes >=8,<12
    - google-auth >=1.6.1
    - cloudpickle
    - kfp-server-api >=1.1.2,<=2.0.0
    - jsonschema >=3.0.1
    - tabulate
    - click
    - Deprecated
    - strip-hints
    - docstring_parser >=0.7.3
    - requests-toolbelt >=0.8.0
    - fire >=0.3.1
    - absl-py >=0.9,<=0.11

test:
  imports:
    - kfp

about:
  home: https://github.com/kubeflow/pipelines
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    Reusable end-to-end ML workflows built using the Kubeflow Pipelines SDK.
  description: |
    Kubeflow is a machine learning (ML) toolkit that is dedicated to making
    deployments of ML workflows on Kubernetes simple, portable, and scalable.
    Kubeflow pipelines are reusable end-to-end ML workflows built using the
    Kubeflow Pipelines SDK.

  doc_url: https://www.kubeflow.org/docs/pipelines/
  dev_url: https://github.com/kubeflow/pipelines/tree/master/sdk/python

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - tanguycdls
    - radcheb
    - ckadner
